version: "3"

services:
    db:
        image: mysql:8.0.33
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "symfony_exchange_app_db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony_exchange_app_network
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/symfony:cached
            - symfony_exchange_app_var:/var/www/symfony/var
            - symfony_exchange_app_vendor:/var/www/symfony/vendor
        networks:
            - symfony_exchange_app_network
    nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/symfony:cached
            - symfony_exchange_app_var:/var/www/symfony/var
            - symfony_exchange_app_vendor:/var/www/symfony/vendor
        ports:
            - 80:80
        networks:
            - symfony_exchange_app_network
        env_file:
            - .env.nginx.local

volumes:
    symfony_exchange_app_var:
    symfony_exchange_app_vendor:
    symfony_exchange_app_db:

networks:
    symfony_exchange_app_network:
